---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwt-secret-sa
  namespace: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jwt-secret-role
  namespace: backend
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jwt-secret-rolebinding
  namespace: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jwt-secret-role
subjects:
  - kind: ServiceAccount
    name: jwt-secret-sa
    namespace: backend
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jwt-secret-generator
  namespace: backend
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: jwt-secret-sa
      restartPolicy: OnFailure
      containers:
        - name: secret-generator
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              if kubectl get secret jwt-secret >/dev/null 2>&1; then
                echo "Secret 'jwt-secret' already exists. Skipping generation."
              else
                echo "Generating new secure JWT secret..."
                SECRET_VAL=$(head -c 32 /dev/urandom | base64 | tr -d '\n')
                kubectl create secret generic jwt-secret --from-literal=JWT_SECRET_KEY=$SECRET_VAL
                echo "Secret created successfully."
              fi
