---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-fallback-ingress
  namespace: frontend
spec:
  # Notice there is NO 'host' field here. 
  # This makes it the global cluster catch-all.
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: error-page
                port:
                  number: 80
