---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: api-image
    newName: ghcr.io/sm26-industrial-software-dev/api
    newTag: latest
  - name: web-ui-image
    newName: ghcr.io/sm26-industrial-software-dev/web-ui:latest
  - name: db-syncer-image
    newName: ghcr.io/sm26-industrial-software-dev/db-syncer:latest
  - name: trade-writer-image
    newName: ghcr.io/sm26-industrial-software-dev/trade-writer:latest
  - name: price-cacher-image
    newName: ghcr.io/sm26-industrial-software-dev/price-cacher:latest

resources:
  # 1. Namespaces must exist before anything else is deployed
  - namespaces.yaml

  # 2. Infrastructure Layer
  - infrastructure/monitoring

  # 3. Data Layer
  - data-layer/postgres
  - data-layer/redis
  - data-layer/pgbouncer

  # 4. Applications Layer
  - apps/error-pages
  - apps/fastapi
  - apps/locust
  - apps/streamlit
  - apps/adminer
  - apps/trade-writer
  - apps/db-syncer
  - apps/price-cacher

configMapGenerator:
  - name: db-routing
    namespace: data
    envs:
      - shared-config/db-routing.env
    options:
      disableNameSuffixHash: true

  - name: db-routing
    namespace: backend
    envs:
      - shared-config/db-routing.env
    options:
      disableNameSuffixHash: true
