---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# This tells K3s to automatically download and install the Loki-Stack Helm Chart
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: kube-system
spec:
  targetNamespace: monitoring
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  # We use a specific version for stability
  version: 2.9.11
  # These are the Helm "values" we override.
  # We turn ON Grafana and Promtail, and tell Promtail to read everything.
  set:
    grafana.enabled: "true"
    loki.persistence.enabled: "false"
    promtail.enabled: "true"
    prometheus.enabled: "true"
    grafana.grafana\.ini.dashboards.default_home_dashboard_path: "/tmp/dashboards/dashboard.json"
    grafana.sidecar.dashboards.enabled: "true"
    grafana.sidecar.dashboards.label: "grafana_dashboard"
    grafana.sidecar.dashboards.searchNamespace: "ALL"
    grafana.sidecar.dashboards.folder: "/tmp/dashboards"
    grafana.sidecar.dashboards.provider.allowUiUpdates: "true"
    grafana.sidecar.dashboards.additionalProviders: |
      - name: loki-official
        orgId: 1
        folder: 'Loki'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /tmp/dashboards
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  rules:
    - host: grafana.localhost # We use a specific host to separate it from your API traffic
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-stack-grafana
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: monitoring
spec:
  rules:
    - host: loki.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-stack
                port:
                  number: 3100
