{
 "title": "k3d Stats",
 "refresh": "5s",
 "panels": [
  {
   "title": "FastAPI Live Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"booklib\"}"
    }
   ]
  },
  {
   "title": "Active FastAPI Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (pod) (container_cpu_usage_seconds_total{namespace=\"backend\", container=\"fastapi\"}))"
    }
   ]
  },
  {
   "title": "FastAPI CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"backend\", container=\"fastapi\"}[1m])) by (pod)"
    }
   ]
  }
 ]
}