---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Define all your standard Kubernetes manifests here
resources:
  - 00-namespaces.yaml
  - 01-fastapi.yaml
  - 02-monitoring.yaml
  - 03-locust.yaml
  - loki-helm-repo.yaml
  - loki-helm-release.yaml

configMapGenerator:
  - name: custom-fastapi-dashboard
    namespace: monitoring
    files:
      - custom-dashboard.json=./dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: "Custom_Dashboards"
