---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: autologin-script
              mountPath: /var/www/html/index.php
              subPath: index.php
      volumes:
        - name: autologin-script
          configMap:
            name: adminer-autologin
