---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/thegreatestgiant/equity-trading-system
  ref:
    branch: main # The branch you are currently working on
