---
apiVersion: v1
kind: Service
metadata:
  name: traefik-bridge
  namespace: backend
spec:
  type: ExternalName
  externalName: traefik.kube-system.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-ui-entry
  namespace: backend
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - ui
  rules:
    - host: ui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-bridge
                port:
                  number: 80
