---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-ui-entry
  namespace: frontend
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - ui
  rules:
    - host: ui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-proxy
                port:
                  number: 80
