# syntax=docker/dockerfile:1

# to build, pass name of desired bin. for example:
# --build-arg BIN_NAME=trade-writer

FROM --platform=$BUILDPLATFORM lukemathwalker/cargo-chef:latest AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json


FROM --platform=$BUILDPLATFORM lukemathwalker/cargo-chef:latest AS builder

RUN apt-get update && apt-get install -y \
    musl-tools \
    wget \
    && rm -rf /var/lib/apt/lists/*
#   ^ reduce layer size by deleting apt lists

# Download and install the aarch64-linux-musl cross-compiler toolchain
RUN wget https://musl.cc/aarch64-linux-musl-cross.tgz && \
    tar -xzf aarch64-linux-musl-cross.tgz -C /usr/local && \
    rm aarch64-linux-musl-cross.tgz

# Add the new toolchain to PATH
ENV PATH="/usr/local/aarch64-linux-musl-cross/bin:${PATH}"

ARG TARGETARCH
ARG RUST_ARCH=${TARGETARCH/amd64/x86_64}
ARG RUST_ARCH=${RUST_ARCH/arm64/aarch64}
ENV RUST_TARGET=${RUST_ARCH}-unknown-linux-musl

# for compiling x64 use musl-gcc
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc
ENV CC_x86_64_unknown_linux_musl=musl-gcc

# for cross-compiling to arm64, link with MUSL aarch64 compiler
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc
ENV CC_aarch64_unknown_linux_musl=aarch64-linux-musl-gcc
ENV CXX_aarch64_unknown_linux_musl=aarch64-linux-musl-g++

RUN rustup target add $RUST_TARGET

COPY --from=planner /recipe.json recipe.json
RUN cargo chef cook --release --target $RUST_TARGET --recipe-path recipe.json

COPY . .
ARG BIN_NAME
RUN cargo build --release --target $RUST_TARGET --bin $BIN_NAME
RUN cp target/$RUST_TARGET/release/$BIN_NAME /app-binary


# final stage assumes the platform requested in the build command
FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app-binary /app-binary
CMD ["/app-binary"]
