---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Enable AOF (Append Only File)
    appendonly yes
    appendfsync everysec

    # Enable RDB (Snapshots: Save after 60 sec if 1 key changed, or 300 sec if 10 changed)
    save 60 1
    save 300 10

    # Where to store the data
    dir /data
