---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          args: ["--loglevel", "verbose"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /data
      volumes:
        - name: config-volume
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
