---
name: Infrastructure - Local Cluster Test

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-cluster-bootstrapping:
    name: Run cluster_up.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Bootstrap k3d & Flux
        env:
          CONTAINER_ENGINE: docker
        run: |
          ./cluster_up.sh
